apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: composite-op
  namespace: calcspringboot
  labels:
    app: composite-op
spec:
  replicas: 1
  strategy: 
    type: Recreate  
  template:
    metadata:
      labels:
        app: composite-op
    spec:
      containers:
      - image: arunimi/composite-op:1.0.0
        name: divide
        imagePullPolicy: Always
        ports:
        - containerPort: 8005
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "docker"
        readinessProbe:
          httpGet:
            path: /actuator
            port: 8005
          initialDelaySeconds: 10
          timeoutSeconds: 10
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8005
          initialDelaySeconds: 60
          timeoutSeconds: 10          
        resources:
          requests:
            cpu: 20m
            memory: 50Mi               
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: composite-op
  namespace: calcspringboot
  labels:
    app: composite-op
  annotations:
    prometheus.io/scrape: 'true' 
    prometheus.io/path: '/actuator/prometheus'     
spec:
  type: ClusterIP
  ports:
  - name: "8005"
    port: 8005
    targetPort: 8005
  selector:
    app: composite-op
