apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: eventprocessor
  namespace: calcspringboot
  labels:
    app: eventprocessor
spec:
  replicas: 1
  strategy: 
    type: Recreate  
  template:
    metadata:
      labels:
        app: eventprocessor
    spec:
      containers:     
      - image: arunimi/calculator-eventprocessor:1.0.0
        name: eventprocessor
        imagePullPolicy: Always
        ports:
        - containerPort: 8007
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "docker"         
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: eventprocessor
  namespace: calcspringboot
  labels:
    app: eventprocessor
  annotations:
    prometheus.io/scrape: 'true' 
    prometheus.io/path: '/actuator/prometheus'     
spec:
  type: ClusterIP
  ports:
  - name: "8007"
    port: 8007
    targetPort: 8007
  selector:
    app: eventprocessor
